config/routes.rb
Rails.application.routes.draw do
  devise_for :professionals 
  resources :professionals, only: %i[show] do 
    resources :profiles, only: %i[ create show index]
  end

  devise_for :users
  resources :projects, only: %i[close] do 
    post 'close', on: :member
  end 
  
  root to: 'home#index'
  
  resources :projects, only: %i[create new show index ] do 
    resources :project_applications, only: %i[create show edit], shallow: true do 
      post 'accept', on: :member
      post 'reject', on: :member
    end
  end
  resources :project_applications, only: %i[ index destroy update ]

  resources :profiles, only: %i[create update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
    <div class="alert alert-info" role="alert">
        <%= flash[:notice].inspect%>
    </div>
<% end%>
<% if flash[:alert]%>
    <div class="alert alert-warning" role="alert">
        <%= flash[:alert]%>
    </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
  <div class="btn btn-danger">
    <% form.object.errors.full_messages.each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>
<% end  %>

app/views/shared/_is_current_professional_profile.html.erb
<li class="nav-item">
  <p><%=link_to current_professional.email, professional_profile_path(:id,current_professional.id), class:"nav-link disabled"%></p>
</li>
<li class="nav-item">
  <p><%= link_to 'Ver aplicações', project_applications_path, class:"nav-link active"%></p>
</li>
<% if current_professional.profile.id?%>
  <li class="nav-item">
    <p><%= link_to 'Veja seu perfil', professional_profile_path(current_professional.id, current_professional.profile.id), class:"nav-link active" %></p>
  </li>
<% end %>
<li class="nav_item">
  <p><%= link_to 'Ver projetos disponíveis', projects_path, class:"nav-link active" %></p>
</li>
<li class="nav-item">
  <p><%= link_to 'Logout', destroy_professional_session_path, method: :delete, class:"nav-link active"%></p>
</li>

app/views/shared/_is_not_current_professional_profile.html.erb
<li class="nav-item">
  <p><%= link_to current_professional.email, current_professional, class:"nav-link disabled"%>
    <p>
    </li>
    <li class="nav-item">
      <p> <%= link_to 'Crie', professional_path(current_professional), class:"nav-link active" %></p>
    </li>
    <li class="nav-item">
      <p><%= link_to 'Logout', destroy_professional_session_path, method: :delete, class:"nav-link " %></p>
    </li>

app/views/shared/_no_one_is_authenticated.html.erb
 
<li class="nav-item">
  <%= link_to 'Entrar como usuário', new_user_session_path, class:"nav-link active" %>
</li>
<li class="nav-item">
  <%= link_to 'Entrar como profissional', new_professional_session_path, class:"nav-link active"%>
</li>

app/views/shared/_user_is_signed_in.html.erb
<li class="nav-item">
  <%= link_to current_user.email, root_path, class:"nav-link active" %>
</li>
<li class="nav-item">
  <p><%= link_to 'Ver aplicações', project_applications_path, class:"nav-link active" %>
  </li>
  <li class="nav-item">
    <p><%= link_to 'Adicionar projeto', new_project_path, class:"nav-link active" %>
    </li>
    <li class="nav-item">
      <p><%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"nav-link active"%>
      </li>