config/routes.rb
Rails.application.routes.draw do
  devise_for :professionals 
  resources :professionals, only: %i[show] do 
    resources :profiles, only: %i[ create show index]
  end

  devise_for :users
  resources :projects, only: %i[close] do 
    post 'close', on: :member
  end 
  
  root to: 'home#index'
  
  resources :projects, only: %i[create new show index ] do 
    resources :project_applications, only: %i[create show edit], shallow: true do 
      post 'accept', on: :member
      post 'reject', on: :member
    end
  end
  resources :project_applications, only: %i[ index destroy update ]

  resources :profiles, only: %i[create update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project_application.rb
class ProjectApplication < ApplicationRecord
  belongs_to :project
  belongs_to :professional

  validates :introduction, presence: true

  enum status: {pending: 5, accepted: 10, rejected: 15}

  def professional_social_name_exists(p)
    if professional.profile && professional.profile.social_name?
    elsif !professional.profile || !p.professional.profile.social_name
      false
    end
  end


  def professional_cannot_cancel_application(p)
     p.updated_at > 3.days.ago
  end
end

app/controllers/project_applications_controller.rb
class ProjectApplicationsController < ApplicationController
  before_action :authenticate_professional!, only: %i[show create destroy update]
  before_action :authenticate_user!, only: %i[accept reject]
  before_action :authenticate, only: %i[index]
  before_action :professional_profile_exists
  before_action :ensures_project_ownership_privileges, only: %i[accept reject]

  helper_method :is_current_professional_signed_in
  helper_method :is_current_user_signed_in

  def index
    @project_application = ProjectApplication.all
  end

  def show
    @project_application = ProjectApplication.find(params[:id])
    @project_application_show = ProjectApplication.where(professional_id: current_professional)
  end

  def create
    if current_professional.project_applications.exists?(id: params[:project_id])
      flash[:alert] = "Já existe"
      redirect_to @project_application.project
    else
      @project_application = current_professional.project_applications.new(project_application_params)
      @project_application.project = Project.find(params[:project_id]) 
      if @project_application.project.closed?
        flash[:alert] = "Esse projeto está fechado!"
        redirect_to @project_application.project
      elsif @project_application.save
        flash[:notice] = 'Você se candidatou para fazer parte desse projeto com sucesso!'
        redirect_to @project_application
      else
        flash[:alert] = @project_application.errors.full_messages.join("\n")
        redirect_to @project_application.project
      end
    end
  end

  def edit
      @project_application = ProjectApplication.find(params[:id])
  end

  def update
    @project_application = ProjectApplication.find(params[:id])
      if @project_application.update(project_application_params)
          redirect_to project_applications_path
      end
  end

  def accept
    @project_application = ProjectApplication.find(params[:id])
    @project_application.accepted!
    redirect_to project_applications_path, notice: "Você aceitou a proposta!"
  end

  def reject
    @project_application = ProjectApplication.find(params[:id])
    @project_application.rejected!
    redirect_to project_applications_path, notice: "Você recusou a proposta!"
  end

  def destroy
    @project_application = ProjectApplication.find(params[:id])
    @project_application.destroy
    redirect_to project_applications_path, notice: "Você cancelou uma proposta!"
  end

  def is_current_professional_signed_in(p)
    professional_signed_in? && current_professional.id == p.professional_id
  end

  def is_current_user_signed_in(p)
    user_signed_in? && p.project.is_owner?(current_user.id)
  end

  def professional_profile_exists
    if professional_signed_in? && !current_professional.profile
      redirect_to current_professional
    end
  end

  private

  def authenticate
    professional_signed_in? || user_signed_in?
  end

  def project_application_params
    params.require(:project_application).permit(:introduction, :reason)
  end

  def ensures_project_ownership_privileges
    if !ProjectApplication.find(params[:id]).project.is_owner?(current_user.id)
      redirect_to project_applications_path, notice: "Você não tem privilégios para executar essa ação!"
    end
  end
end

app/views/project_applications/edit.html.erb
<%= form_with model:[@projects, @project_application], local: true do |f| %>
  <% if f.object.errors.any? %>
    <div class="btn btn-danger">
      <% f.object.errors.full_messages.each do |message|%>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div>
    <%= f.label :reason, "Justificativa" %>
    <%= f.text_field :reason %>
  </div>
  <div><%=f.submit 'Cancelar'%></div>
<% end %>

app/views/project_applications/index.html.erb
  <% @project_application.each do |p|%>
  <% if p.errors.any? %>
    <div class="btn btn-danger">
      <% p.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <% if p.project.closed? && (p.rejected? || p.pending?)%>
  <%elsif is_current_professional_signed_in(p) %>
    <div>
      <p>Projeto: <%= p.project.title%></p>
      <p>Introdução <%= p.introduction%></p>
    </div>
  <% end %>
  <% if is_current_professional_signed_in(p) && p.reason%>
    <p class="alert alert-primary" role="alert">Você cancelou essa aplicação com a justificativa de: <%= p.reason%></p>
  <% elsif is_current_professional_signed_in(p) && p.pending? && p.project.active? && !p.project.exceed_deadline?%>
    <p class="alert alert-primary" role="alert">Sua candidatura está pendente</p>
    <p><%=link_to "Cancelar sua aplicação", project_application_path(p, p.id), method: :delete %></p>
  <% elsif is_current_professional_signed_in(p) && p.accepted?  %>
    <% if p.professional_cannot_cancel_application(p) %>
      <p class="alert alert-success" role="alert"> Sua candidatura foi aceita! </p>
      <p><%=link_to "Cancele sua aplicação", edit_project_application_path(p, p.id) %></p>
    <% else %>
      <p class="alert alert-success" role="alert"> Sua candidatura foi aceita! </p>
    <% end %>
  <% elsif is_current_professional_signed_in(p) && p.rejected? && p.project.active? %>
    <p class="alert alert-danger" role="alert">Sua candidatura foi recusada mas não desanime! Temos muitos projetos que encaixam no seu perfil</p>
  <% elsif p.project.closed? %>
    <p class="alert alert-danger" role="alert">Inscrições fechadas</p>
     <% elsif p.project.exceed_deadline? %>
    <p class="alert alert-danger" role="alert">Inscrições fechadas</p>
  <% end %>
<% end %>
<% if user_signed_in?%>
  <p>Candidaturas</p>
  <% @project_application.each do |p|%>
    <div class="row">
      <% if is_current_user_signed_in(p) && !p.reason %>
        <div class="row-lg-100">
          <div class="card" >
            <div class="card-body">
              <h5 class="card-title"><%= p.project.title%></h5>
              <dt>Introdução</dt>
              <h6 clas="card-subtitle"><%= p.introduction%></h6>
              <dt>Nome do profissional:</dt>
              <% if p.professional_social_name_exists(p) %>
                <h6 class="card-text"> <%= p.professional.profile.social_name %></h6>
              <% else %>
                <h6 class="card-text"> <%= p.professional.profile.full_name %></h6>
              <% end %>
              <dt>Mande um email para contatar o profissional:</dt>
              <h6 class="card-text"> <%=mail_to p.professional.email%></h6>
              <dt>Data de nascimento:</dt>
              <h6 class="card-text"><%= p.professional.profile.birth_date.strftime("%d/%m/%Y") %></h6>
              <dt>Status:</dt>
              <dd><%= p.status%></dd>
              <% if p.pending? && !p.project.closed?%>
                <p><%= link_to 'Aceitar', accept_project_application_path(p.id), method: :post, class: "btn btn-primary" %></p>
                <p><%= link_to 'Recusar', reject_project_application_path(p.id), method: :post, class: "btn btn-primary" %></p>
              <% end %>
              <% if p.project.closed?%>
                <p class="alert alert-warning" role="alert">Você encerrou as inscrições para este projeto!</p>
              <% elsif p.project.deadline < DateTime.current%>
                <p class="alert alert-warning" role="alert">Data limite para profissionais aplicarem para o projeto expirou</p>
              <% end %>
            </div>
          </div>
          <div>
          <% elsif p.reason? %>
            <div class="row">
              <div class="row-lg-100">
                <div class="card" >
                  <div class="card-body">
                    <h5 class="card-title">Motivo:</h5>
                    <h6 clas="card-subtitle"><%= p.reason%></h6>
                    <% if p.professional_social_name_exists(p)%>
                      <p class="alert alert-danger" role="alert"><%= p.professional.profile.social_name%> cancelou a aplicação</p>
                    <% else %>
                      <p class="alert alert-danger" role="alert"><%= p.professional.profile.full_name%> cancelou a aplicação</p>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>

app/views/project_applications/show.html.erb
<% if @project_application.project.errors.any? %>
  <ul>
    <% @project_application.project.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<% if user_signed_in? %>
  <h1>Aplicações para o projeto <%= @project_application.project.title%></h1>
  <dl>
    <dt>Introdução </dt>
    <dd><%= @project_application.introduction%></dd>
  </dl>
<% end %>
<% if professional_signed_in? && current_professional.project_applications%>
  <h1>Sua Aplicação para o projeto <%= @project_application.project.title%></h1>
  <dl>
    <dt>Introdução: </dt>
    <dd><%= @project_application.introduction%></dd>
  </dl>
<% end %>